openapi: 3.0.0
info:
  description: Description of the User API
  title: User API
  version: 1.1.1
servers:
- description: Anypoint Cloudhub
  url: https://anypoint.mulesoft.com/accounts/api/
- description: Anypoint Cloudhub EU
  url: https://eu1.anypoint.mulesoft.com/accounts/api/
- description: Anypoint Cloudhub GOV
  url: https://gov.anypoint.mulesoft.com/accounts/api/
security:
- bearerAuth: []
paths:
  /organizations/{orgId}/users:
    get:
      description: Returns the group of users that belong to the specified organization.
      operationId: listUsers
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: A search string to specify the type of user you want to retrieve.
        explode: true
        in: query
        name: type
        required: false
        schema:
          enum:
          - host
          - proxy
          - all
          type: string
        style: form
      - description: Maximum number of users to retrieve per request.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: The number of records to omit from the response.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUsersResponse'
          description: Success response
    post:
      description: Creates a User
      operationId: createUser
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPostBody'
      responses:
        "401":
          description: Access token is missing or invalid
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createUser_400_response'
          description: Bad request response
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Success response
  /organizations/{orgId}/users/{userId}:
    delete:
      description: Delete the user
      operationId: deleteUser
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: the ID of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          description: Success response
    get:
      description: Returns a specific user that belong to the specified organization.
      operationId: getUser
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: the ID of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Success response
    put:
      description: Update a user
      operationId: updateUser
      parameters:
      - description: The ID of the organization in GUID format
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      - description: the ID of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPutBody'
      responses:
        "401":
          description: Access token is missing or invalid
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createUser_400_response'
          description: Bad request response
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Success response
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createUser_400_response'
      description: Bad request response
    SuccessPostUser:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: Success response
    SuccessPutUser:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: Success response
    SuccessDeleteUser:
      description: Success response
    SuccessListUsers:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListUsersResponse'
      description: Success response
    SuccessGetUser:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: Success response
  schemas:
    ListUsersResponse:
      example:
        total: 0
        data:
        - lastName: Mule
          lastLogin: 2021-07-12T09:28:43.569Z
          mfaVerifiersConfigured: "false"
          type: type
          memberOfOrganizations:
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          enabled: true
          contributorOfOrganizations:
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          isFederated: false
          organizationId: xxxxxx-213d-4f60-845c-207286484cd1
          mfaVerificationExcluded: false
          firstName: Uzer
          createdAt: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
          phoneNumber: 111-111-1111
          deleted: false
          organization:
            isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          organizationPreferences: "{}"
          id: 4b353f44-6486-42ae-ae77-18b4032f9643
          primaryOrganization:
            name: name
            id: id
          idprovider_id: mulesoft
          email: api.platform.qa+uzer@gmail.com
          properties:
            cs_auth: "{}"
          username: UzerMule.test
          updatedAt: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
        - lastName: Mule
          lastLogin: 2021-07-12T09:28:43.569Z
          mfaVerifiersConfigured: "false"
          type: type
          memberOfOrganizations:
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          enabled: true
          contributorOfOrganizations:
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          - isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          isFederated: false
          organizationId: xxxxxx-213d-4f60-845c-207286484cd1
          mfaVerificationExcluded: false
          firstName: Uzer
          createdAt: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
          phoneNumber: 111-111-1111
          deleted: false
          organization:
            isAutomaticAdminPromotionExempt: true
            entitlements: "{}"
            subOrganizationIds:
            - subOrganizationIds
            - subOrganizationIds
            clientId: clientId
            tenantOrganizationIds:
            - tenantOrganizationIds
            - tenantOrganizationIds
            subscription:
              expiration: expiration
              category: category
              type: type
            ownerId: ownerId
            isFederated: true
            createdAt: createdAt
            isMaster: true
            domain: domain
            name: name
            id: id
            mfaRequired: mfaRequired
            idprovider_id: idprovider_id
            properties: "{}"
            updatedAt: updatedAt
            parentOrganizationIds:
            - parentOrganizationIds
            - parentOrganizationIds
          organizationPreferences: "{}"
          id: 4b353f44-6486-42ae-ae77-18b4032f9643
          primaryOrganization:
            name: name
            id: id
          idprovider_id: mulesoft
          email: api.platform.qa+uzer@gmail.com
          properties:
            cs_auth: "{}"
          username: UzerMule.test
          updatedAt: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
      properties:
        data:
          items:
            $ref: '#/components/schemas/User'
          title: UserList
          type: array
        total:
          title: Total number of results
          type: integer
      title: ListUsersResponse
      type: object
    UserList:
      items:
        $ref: '#/components/schemas/User'
      title: UserList
      type: array
    UserPostBody:
      example:
        firstName: firstName
        lastName: lastName
        password: password
        phoneNumber: phoneNumber
        email: email
        username: username
      properties:
        username:
          title: username
          type: string
        firstName:
          title: firstName
          type: string
        lastName:
          title: lastName
          type: string
        email:
          title: email
          type: string
        phoneNumber:
          title: phoneNumber
          type: string
        password:
          title: password
          type: string
      title: UserPostBody
      type: object
    UserPutBody:
      example:
        firstName: firstName
        lastName: lastName
        password: password
        phoneNumber: phoneNumber
        email: email
        properties: "{}"
        username: username
      properties:
        username:
          title: username
          type: string
        firstName:
          title: firstName
          type: string
        lastName:
          title: lastName
          type: string
        email:
          title: email
          type: string
        phoneNumber:
          title: phoneNumber
          type: string
        password:
          title: password
          type: string
        properties:
          title: properties
          type: object
      title: UserPutBody
      type: object
    User:
      allOf:
      - properties:
          id:
            description: The user Id
            example: 4b353f44-6486-42ae-ae77-18b4032f9643
            title: id
            type: string
        required:
        - id
        title: userId
        type: object
      - $ref: '#/components/schemas/UserCore'
      example:
        lastName: Mule
        lastLogin: 2021-07-12T09:28:43.569Z
        mfaVerifiersConfigured: "false"
        type: type
        memberOfOrganizations:
        - isAutomaticAdminPromotionExempt: true
          entitlements: "{}"
          subOrganizationIds:
          - subOrganizationIds
          - subOrganizationIds
          clientId: clientId
          tenantOrganizationIds:
          - tenantOrganizationIds
          - tenantOrganizationIds
          subscription:
            expiration: expiration
            category: category
            type: type
          ownerId: ownerId
          isFederated: true
          createdAt: createdAt
          isMaster: true
          domain: domain
          name: name
          id: id
          mfaRequired: mfaRequired
          idprovider_id: idprovider_id
          properties: "{}"
          updatedAt: updatedAt
          parentOrganizationIds:
          - parentOrganizationIds
          - parentOrganizationIds
        - isAutomaticAdminPromotionExempt: true
          entitlements: "{}"
          subOrganizationIds:
          - subOrganizationIds
          - subOrganizationIds
          clientId: clientId
          tenantOrganizationIds:
          - tenantOrganizationIds
          - tenantOrganizationIds
          subscription:
            expiration: expiration
            category: category
            type: type
          ownerId: ownerId
          isFederated: true
          createdAt: createdAt
          isMaster: true
          domain: domain
          name: name
          id: id
          mfaRequired: mfaRequired
          idprovider_id: idprovider_id
          properties: "{}"
          updatedAt: updatedAt
          parentOrganizationIds:
          - parentOrganizationIds
          - parentOrganizationIds
        enabled: true
        contributorOfOrganizations:
        - isAutomaticAdminPromotionExempt: true
          entitlements: "{}"
          subOrganizationIds:
          - subOrganizationIds
          - subOrganizationIds
          clientId: clientId
          tenantOrganizationIds:
          - tenantOrganizationIds
          - tenantOrganizationIds
          subscription:
            expiration: expiration
            category: category
            type: type
          ownerId: ownerId
          isFederated: true
          createdAt: createdAt
          isMaster: true
          domain: domain
          name: name
          id: id
          mfaRequired: mfaRequired
          idprovider_id: idprovider_id
          properties: "{}"
          updatedAt: updatedAt
          parentOrganizationIds:
          - parentOrganizationIds
          - parentOrganizationIds
        - isAutomaticAdminPromotionExempt: true
          entitlements: "{}"
          subOrganizationIds:
          - subOrganizationIds
          - subOrganizationIds
          clientId: clientId
          tenantOrganizationIds:
          - tenantOrganizationIds
          - tenantOrganizationIds
          subscription:
            expiration: expiration
            category: category
            type: type
          ownerId: ownerId
          isFederated: true
          createdAt: createdAt
          isMaster: true
          domain: domain
          name: name
          id: id
          mfaRequired: mfaRequired
          idprovider_id: idprovider_id
          properties: "{}"
          updatedAt: updatedAt
          parentOrganizationIds:
          - parentOrganizationIds
          - parentOrganizationIds
        isFederated: false
        organizationId: xxxxxx-213d-4f60-845c-207286484cd1
        mfaVerificationExcluded: false
        firstName: Uzer
        createdAt: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
        phoneNumber: 111-111-1111
        deleted: false
        organization:
          isAutomaticAdminPromotionExempt: true
          entitlements: "{}"
          subOrganizationIds:
          - subOrganizationIds
          - subOrganizationIds
          clientId: clientId
          tenantOrganizationIds:
          - tenantOrganizationIds
          - tenantOrganizationIds
          subscription:
            expiration: expiration
            category: category
            type: type
          ownerId: ownerId
          isFederated: true
          createdAt: createdAt
          isMaster: true
          domain: domain
          name: name
          id: id
          mfaRequired: mfaRequired
          idprovider_id: idprovider_id
          properties: "{}"
          updatedAt: updatedAt
          parentOrganizationIds:
          - parentOrganizationIds
          - parentOrganizationIds
        organizationPreferences: "{}"
        id: 4b353f44-6486-42ae-ae77-18b4032f9643
        primaryOrganization:
          name: name
          id: id
        idprovider_id: mulesoft
        email: api.platform.qa+uzer@gmail.com
        properties:
          cs_auth: "{}"
        username: UzerMule.test
        updatedAt: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
      title: user
    UserCore:
      properties:
        username:
          example: UzerMule.test
          title: username
          type: string
        firstName:
          example: Uzer
          title: firstName
          type: string
        lastName:
          default: Mule
          title: lastName
          type: string
        phoneNumber:
          example: 111-111-1111
          title: phoneNumber
          type: string
        email:
          example: api.platform.qa+uzer@gmail.com
          title: email
          type: string
        organizationId:
          example: xxxxxx-213d-4f60-845c-207286484cd1
          title: organizationId
          type: string
        enabled:
          example: true
          title: enabled
          type: boolean
        deleted:
          example: false
          title: deleted
          type: boolean
        lastLogin:
          example: 2021-07-12T09:28:43.569Z
          title: lastLogin
          type: string
        mfaVerificationExcluded:
          example: false
          title: mfaVerificationExcluded
          type: boolean
        mfaVerifiersConfigured:
          example: "false"
          title: mfaVerifiersConfigured
          type: string
        idprovider_id:
          example: mulesoft
          title: idproviderId
          type: string
        createdAt:
          example: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
          title: createdAt
          type: string
        updatedAt:
          example: Mon Feb 09 2015 17:47:26 GMT-0300 (ART)
          title: updatedAt
          type: string
        isFederated:
          example: false
          title: isFederated
          type: boolean
        type:
          title: type
          type: string
        organization:
          $ref: '#/components/schemas/Organization'
        memberOfOrganizations:
          items:
            $ref: '#/components/schemas/Organization'
          title: MemberOfOrganizations
          type: array
        contributorOfOrganizations:
          items:
            $ref: '#/components/schemas/Organization'
          title: ContributorOfOrganizations
          type: array
        properties:
          $ref: '#/components/schemas/properties'
        organizationPreferences:
          title: organizationPreferences
          type: object
        primaryOrganization:
          $ref: '#/components/schemas/primaryOrganization'
      title: UserCore
      type: object
    Organization:
      example:
        isAutomaticAdminPromotionExempt: true
        entitlements: "{}"
        subOrganizationIds:
        - subOrganizationIds
        - subOrganizationIds
        clientId: clientId
        tenantOrganizationIds:
        - tenantOrganizationIds
        - tenantOrganizationIds
        subscription:
          expiration: expiration
          category: category
          type: type
        ownerId: ownerId
        isFederated: true
        createdAt: createdAt
        isMaster: true
        domain: domain
        name: name
        id: id
        mfaRequired: mfaRequired
        idprovider_id: idprovider_id
        properties: "{}"
        updatedAt: updatedAt
        parentOrganizationIds:
        - parentOrganizationIds
        - parentOrganizationIds
      properties:
        name:
          title: name
          type: string
        id:
          title: id
          type: string
        createdAt:
          title: createdAt
          type: string
        updatedAt:
          title: updatedAt
          type: string
        ownerId:
          title: ownerId
          type: string
        clientId:
          title: clientId
          type: string
        idprovider_id:
          title: idprovider_id
          type: string
        isFederated:
          title: isFederated
          type: boolean
        parentOrganizationIds:
          items:
            type: string
          title: parentOrganizationIds
          type: array
        subOrganizationIds:
          items:
            type: string
          title: subOrganizationIds
          type: array
        tenantOrganizationIds:
          items:
            type: string
          title: tenantOrganizationIds
          type: array
        mfaRequired:
          title: mfaRequired
          type: string
        isAutomaticAdminPromotionExempt:
          title: isAutomaticAdminPromotionExempt
          type: boolean
        domain:
          title: domain
          type: string
        isMaster:
          title: isMaster
          type: boolean
        subscription:
          $ref: '#/components/schemas/subscription'
        properties:
          title: properties
          type: object
        entitlements:
          title: entitlements
          type: object
      title: Organization
      type: object
    MemberOfOrganizations:
      items:
        $ref: '#/components/schemas/Organization'
      title: MemberOfOrganizations
      type: array
    ContributorOfOrganizations:
      items:
        $ref: '#/components/schemas/Organization'
      title: ContributorOfOrganizations
      type: array
    createUser_400_response:
      example:
        message: A sample message here
        status: 0
      properties:
        status:
          default: 400
          title: the response status code
          type: integer
        message:
          example: A sample message here
          title: the error message
          type: string
      type: object
    properties:
      example:
        cs_auth: "{}"
      properties:
        cs_auth:
          title: cs_auth
          type: object
      title: properties
      type: object
    primaryOrganization:
      example:
        name: name
        id: id
      properties:
        id:
          title: id
          type: string
        name:
          title: name
          type: string
      title: primaryOrganization
      type: object
    subscription:
      example:
        expiration: expiration
        category: category
        type: type
      properties:
        category:
          title: category
          type: string
        type:
          title: type
          type: string
        expiration:
          title: expiration
          type: string
      title: subscription
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
