openapi: 3.0.0
info:
  description: Description of the Organization API
  title: Organization API
  version: 1.1.1
servers:
- description: Anypoint Cloudhub
  url: https://anypoint.mulesoft.com/accounts/api/
- description: Anypoint Cloudhub EU
  url: https://eu1.anypoint.mulesoft.com/accounts/api/
- description: Anypoint Cloudhub GOV
  url: https://gov.anypoint.mulesoft.com/accounts/api/
security:
- bearerAuth: []
paths:
  /organizations:
    post:
      description: Creates a new Business Group. This action can only be performed
        with an access token generated from user/pwd.
      operationId: createBG
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BGPostReqBody'
        description: Business Group Request Body Object
        required: true
      responses:
        "401":
          description: Access token is missing or invalid
        "400":
          content:
            text/html:
              schema:
                example: Organization Name provided is empty
                title: the error message
                type: string
          description: Bad request response
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BGCore'
          description: Success response
      summary: Creates a new Business Group.
  /organizations/{orgId}:
    delete:
      description: Delete a Business Group by its given id.
      operationId: deleteBG
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          content:
            application/json:
              schema:
                type: object
          description: Success response
      summary: Delete a Business Group by its id.
    get:
      description: Returns the Business Group with the given id
      operationId: getBG
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterBGDetail'
          description: Success response
      summary: Returns the Business Group instance with the given id.
    put:
      description: Update a Business Group by its given id.
      operationId: updateBG
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BGUpdateReqBody'
        description: Business Group Request Body Object
        required: true
      responses:
        "401":
          description: Access token is missing or invalid
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BGCore'
          description: Success response
      summary: Update a Business Group by its id.
  /cs/organizations/{orgId}/usage:
    get:
      description: Returns the usage for a given Business Group
      operationId: getBGUsage
      parameters:
      - description: The organization Id
        explode: false
        in: path
        name: orgId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "401":
          description: Access token is missing or invalid
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usage'
          description: Success response
      summary: Returns the usage for a given Business Group.
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      content:
        text/html:
          schema:
            example: Organization Name provided is empty
            title: the error message
            type: string
      description: Bad request response
    SuccessGetBG:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MasterBGDetail'
      description: Success response
    SuccessPostBG:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BGCore'
      description: Success response
    SuccessDeleteBG:
      content:
        application/json:
          schema:
            type: object
      description: Success response
    SuccessUpdateBG:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BGCore'
      description: Success response
    SuccessGetUsage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Usage'
      description: Success response
  schemas:
    BGPostReqBody:
      example:
        entitlements:
          globalDeployment: false
          staticIps:
            reassigned: 4
            assigned: 1
          createSubOrgs: false
          loadBalancer:
            reassigned: 7
            assigned: 2
          vpns:
            reassigned: 6
            assigned: 2
          vCoresSandbox:
            reassigned: 3.5571952270680973
            assigned: 6.438423552598547
          vCoresProduction:
            reassigned: 9.018348186070783
            assigned: 8.762042012749001
          createEnvironments: false
          vCoresDesign:
            reassigned: 6.683562403749608
            assigned: 9.369310271410669
          vpcs:
            reassigned: 1
            assigned: 6
        name: name
        ownerId: ownerId
        parentOrganizationId: parentOrganizationId
      properties:
        entitlements:
          $ref: '#/components/schemas/EntitlementsCore'
        name:
          default: ""
          description: The name of the organization
          title: name
          type: string
        ownerId:
          default: ""
          description: The id of the owner of the organization.
          title: ownerId
          type: string
        parentOrganizationId:
          default: ""
          description: a reference to the parent organization
          title: parentOrganizationId
          type: string
      required:
      - entitlements
      - name
      - ownerId
      - parentOrganizationId
      title: BGPostReqBody
      type: object
    BGUpdateReqBody:
      example:
        entitlements:
          globalDeployment: false
          staticIps:
            reassigned: 4
            assigned: 1
          createSubOrgs: false
          loadBalancer:
            reassigned: 7
            assigned: 2
          vpns:
            reassigned: 6
            assigned: 2
          vCoresSandbox:
            reassigned: 3.5571952270680973
            assigned: 6.438423552598547
          vCoresProduction:
            reassigned: 9.018348186070783
            assigned: 8.762042012749001
          createEnvironments: false
          vCoresDesign:
            reassigned: 6.683562403749608
            assigned: 9.369310271410669
          vpcs:
            reassigned: 1
            assigned: 6
        name: name
        sessionTimeout: 0
        ownerId: ownerId
      properties:
        entitlements:
          $ref: '#/components/schemas/EntitlementsCore'
        name:
          default: ""
          description: The name of the organization
          title: name
          type: string
        ownerId:
          default: ""
          description: The id of the owner of the organization.
          title: ownerId
          type: string
        sessionTimeout:
          default: 0
          description: The session timeout in minutes
          title: sessionTimeout
          type: integer
      title: BGUpdateReqBody
      type: object
    BGCore:
      example:
        entitlements:
          workerLoggingOverride:
            enabled: false
          globalDeployment: true
          managedGatewaySmall:
            reassigned: 3
            assigned: 7
          networkConnections:
            reassigned: 3
            assigned: 5
          crowd:
            environments: false
            hideApiManagerDesigner: false
            hideFormerApiPlatform: false
          apiGovernance:
            apisPerMonth: 6
            enabled: true
          telemetryExporter:
            enabled: false
          monitoringCenter:
            preProductionUnits: 1.2315135367772556
            productSKU: 3
            storageAddOn: 4.145608029883936
            storageBase: 2.027123023002322
            productionUnits: 7.386281948385884
            dataRegion: dataRegion
          highAvailability:
            clustering: true
          usageBasedPricingLimits:
            memory:
              extra: 8
              base: 4
            cpu:
              extra: 8
              base: 4
          apiManager:
            usageBasedPricing:
              api:
                production:
                  amount: 3
                sandbox:
                  amount: 3
            governance:
              enabled: false
          objectStoreKeys:
            addOn: 1
            base: 1
          workerClouds:
            reassigned: 5
            assigned: 6
          vCoresDesign:
            reassigned: 6.683562403749608
            assigned: 9.369310271410669
          vpcs:
            reassigned: 1
            assigned: 6
          gateways:
            assigned: 5
          appViz: true
          apiCommunityManager:
            enabled: false
          hybridInsight: true
          apiQuery:
            productSKU: 6
            production: 5
            sandbox: 1
            enabled: false
          objectStoreRequestUnits:
            addOn: 1
            base: 1
          messaging:
            assigned: 9
          tradingPartnersProduction:
            assigned: 5
          muleDxEDA:
            enabled: false
          angGovernance:
            level: -1
          anypointSecurityTokenization:
            enabled: false
          hybrid:
            enabled: false
          cloudhub1:
            enabled: false
          apis:
            enabled: false
          staticIps:
            reassigned: 4
            assigned: 1
          idp:
            enabled: false
          runtimeFabricCloud:
            enabled: false
          muleDxWebIde:
            enabled: false
          kpiDashboard:
            enabled: false
          autoscaling: true
          partnersSandbox:
            assigned: 7
          externalIdentity: true
          usageBasedPricing:
            muleRuntimeIntegration:
              flows: 7
              messages: 6
              throughput: 0
              enabled: false
          hybridAutoDiscoverProperties: true
          vpns:
            reassigned: 6
            assigned: 2
          muleDxGenAI:
            enabled: false
          runtimeFabric: true
          serviceMesh:
            enabled: false
          cam:
            enabled: false
          anypointSecurityEdgePolicies:
            enabled: false
          pcf: true
          armAlerts: true
          createSubOrgs: true
          loadBalancer:
            reassigned: 7
            assigned: 2
          mqMessages:
            addOn: 1
            base: 1
          vCoresSandbox:
            reassigned: 3.5571952270680973
            assigned: 6.438423552598547
          createEnvironments: true
          rpa:
            active: true
            composerVersion: composerVersion
            enabled: true
          apiMonitoring:
            schedules: 0
          composer:
            unlimitedConnectors: true
            tasksPerMonth: 7
            maxConnectors: 0
            isHyperAutomation: true
            enabled: true
          tradingPartnersSandbox:
            assigned: 9
          apiCatalog:
            enabled: false
          managedGatewayLarge:
            reassigned: 7
            assigned: 3
          mqRequests:
            addOn: 1
            base: 1
          apiQueryC360:
            enabled: false
          apiGovernanceDomain:
            domain: domain
          partnersProduction:
            assigned: 6
          exchange2:
            enabled: true
            assetUsageAndEngagement:
              enabled: true
          mqAdvancedFeatures:
            enabled: false
          vCoresProduction:
            reassigned: 9.018348186070783
            assigned: 8.762042012749001
          crowdSelfServiceMigration:
            enabled: false
          designCenter:
            apiVisual: true
            api: true
            apiExample: true
            mozart: true
        isAutomaticAdminPromotionExempt: false
        owner:
          lastLogin: lastLogin
          lastName: lastName
          mfaVerifiersConfigured: mfaVerifiersConfigured
          type: type
          enabled: false
          mfaVerificationExcluded: false
          organizationId: organizationId
          createdAt: createdAt
          firstName: firstName
          deleted: false
          phoneNumber: phoneNumber
          id: id
          idprovider_id: idprovider_id
          email: email
          updatedAt: updatedAt
          username: username
        subOrganizationIds:
        - subOrganizationIds
        - subOrganizationIds
        clientId: "[\"1ab4bb7db66448be902379d1fcfb1a43\"]"
        isRoot: false
        environments:
        - organizationId: organizationId
          clientId: clientId
          isProduction: false
          name: name
          id: id
          type: type
        - organizationId: organizationId
          clientId: clientId
          isProduction: false
          name: name
          id: id
          type: type
        tenantOrganizationIds:
        - tenantOrganizationIds
        - tenantOrganizationIds
        ownerId: ownerId
        isFederated: false
        createdAt: "[\"2021-03-05T14:06:52.976Z\"]"
        isMaster: false
        domain: "[\"ms-04\"]"
        name: name
        id: id
        mfaRequired: mfaRequired
        idprovider_id: idprovider_id
        properties: "{}"
        parentOrganizationIds:
        - parentOrganizationIds
        - parentOrganizationIds
        updatedAt: updatedAt
      properties:
        clientId:
          default: ""
          description: The client id of the organization
          example: "[\"1ab4bb7db66448be902379d1fcfb1a43\"]"
          title: clientId
          type: string
        createdAt:
          default: ""
          description: The creation date of the organization
          example: "[\"2021-03-05T14:06:52.976Z\"]"
          title: createdAt
          type: string
        domain:
          default: ""
          description: The domain of the organization
          example: "[\"ms-04\"]"
          title: domain
          type: string
        entitlements:
          $ref: '#/components/schemas/Entitlements'
        environments:
          description: List of environments.
          items:
            $ref: '#/components/schemas/Environment'
          title: environments
          type: array
        id:
          default: ""
          description: The id of the organization
          title: id
          type: string
        idprovider_id:
          default: ""
          description: The id of the idprovider of the organization.
          title: idprovider_id
          type: string
        isAutomaticAdminPromotionExempt:
          default: false
          description: Whether the organization is exempt from automatic admin promotion.
          title: isAutomaticAdminPromotionExempt
          type: boolean
        isFederated:
          default: false
          description: Whether the organization is federated.
          title: isFederated
          type: boolean
        isRoot:
          default: false
          description: Whether the organization is a root organization.
          title: isRoot
          type: boolean
        isMaster:
          default: false
          description: Whether the organization is a master organization.
          title: isMaster
          type: boolean
        mfaRequired:
          default: ""
          description: Whether multi-factor authentication is required for the organization.
          title: mfaRequired
          type: string
        name:
          default: ""
          description: The name of the organization.
          title: name
          type: string
        ownerId:
          default: ""
          description: The id of the owner of the organization.
          title: ownerId
          type: string
        parentOrganizationIds:
          description: The ids of the parent organizations.
          items:
            title: parentOrganizationId
            type: string
          title: parentOrganizationIds
          type: array
        properties:
          description: The properties of the organization.
          title: properties
          type: object
        subOrganizationIds:
          description: The ids of the sub organizations.
          items:
            default: ""
            description: The id of a sub organization.
            title: subOrganizationId
            type: string
          title: subOrganizationIds
          type: array
        tenantOrganizationIds:
          description: The ids of the tenant organizations.
          items:
            title: tenantOrganizationId
            type: string
          title: tenantOrganizationIds
          type: array
        updatedAt:
          default: ""
          description: The last update date of the organization.
          title: updatedAt
          type: string
        owner:
          $ref: '#/components/schemas/User'
      title: BGCore
      type: object
    MasterBGDetail:
      allOf:
      - $ref: '#/components/schemas/BGCore'
      - $ref: '#/components/schemas/masterBGSpecificDetails'
      title: masterBGDetail
    Environment:
      description: an instance of an environment.
      example:
        organizationId: organizationId
        clientId: clientId
        isProduction: false
        name: name
        id: id
        type: type
      properties:
        clientId:
          default: ""
          description: The client id of the environment.
          title: clientId
          type: string
        id:
          default: ""
          description: The id of the environment.
          title: id
          type: string
        isProduction:
          default: false
          description: Whether the environment is a production environment.
          title: isProduction
          type: boolean
        name:
          default: ""
          description: The name of the environment.
          title: name
          type: string
        organizationId:
          default: ""
          description: The id of the organization.
          title: organizationId
          type: string
        type:
          default: ""
          description: The type of the environment.
          title: type
          type: string
      title: environment
      type: object
    User:
      example:
        lastLogin: lastLogin
        lastName: lastName
        mfaVerifiersConfigured: mfaVerifiersConfigured
        type: type
        enabled: false
        mfaVerificationExcluded: false
        organizationId: organizationId
        createdAt: createdAt
        firstName: firstName
        deleted: false
        phoneNumber: phoneNumber
        id: id
        idprovider_id: idprovider_id
        email: email
        updatedAt: updatedAt
        username: username
      properties:
        createdAt:
          default: ""
          description: The creation date of the user.
          title: createdAt
          type: string
        deleted:
          default: false
          description: Whether the user is deleted.
          title: deleted
          type: boolean
        email:
          default: ""
          description: The email of the user.
          title: email
          type: string
        enabled:
          default: false
          description: Whether the user is enabled.
          title: enabled
          type: boolean
        firstName:
          default: ""
          description: The first name of the user.
          title: firstName
          type: string
        id:
          default: ""
          description: The id of the user.
          title: id
          type: string
        idprovider_id:
          default: ""
          description: The idprovider id of the user.
          title: idprovider_id
          type: string
        lastLogin:
          default: ""
          description: The last login date of the user.
          title: lastLogin
          type: string
        lastName:
          default: ""
          description: The last name of the user.
          title: lastName
          type: string
        mfaVerificationExcluded:
          default: false
          description: Whether the user is excluded from MFA verification.
          title: mfaVerificationExcluded
          type: boolean
        mfaVerifiersConfigured:
          default: ""
          description: Whether the user has configured MFA verifiers.
          title: mfaVerifiersConfigured
          type: string
        organizationId:
          default: ""
          description: The id of the organization.
          title: organizationId
          type: string
        phoneNumber:
          default: ""
          description: The phone number of the user.
          title: phoneNumber
          type: string
        type:
          default: ""
          description: The type of the user.
          title: type
          type: string
        updatedAt:
          default: ""
          description: The last update date of the user.
          title: updatedAt
          type: string
        username:
          default: ""
          description: The username of the user.
          title: username
          type: string
      type: object
    Entitlements:
      description: Business Group entitlements
      example:
        workerLoggingOverride:
          enabled: false
        globalDeployment: true
        managedGatewaySmall:
          reassigned: 3
          assigned: 7
        networkConnections:
          reassigned: 3
          assigned: 5
        crowd:
          environments: false
          hideApiManagerDesigner: false
          hideFormerApiPlatform: false
        apiGovernance:
          apisPerMonth: 6
          enabled: true
        telemetryExporter:
          enabled: false
        monitoringCenter:
          preProductionUnits: 1.2315135367772556
          productSKU: 3
          storageAddOn: 4.145608029883936
          storageBase: 2.027123023002322
          productionUnits: 7.386281948385884
          dataRegion: dataRegion
        highAvailability:
          clustering: true
        usageBasedPricingLimits:
          memory:
            extra: 8
            base: 4
          cpu:
            extra: 8
            base: 4
        apiManager:
          usageBasedPricing:
            api:
              production:
                amount: 3
              sandbox:
                amount: 3
          governance:
            enabled: false
        objectStoreKeys:
          addOn: 1
          base: 1
        workerClouds:
          reassigned: 5
          assigned: 6
        vCoresDesign:
          reassigned: 6.683562403749608
          assigned: 9.369310271410669
        vpcs:
          reassigned: 1
          assigned: 6
        gateways:
          assigned: 5
        appViz: true
        apiCommunityManager:
          enabled: false
        hybridInsight: true
        apiQuery:
          productSKU: 6
          production: 5
          sandbox: 1
          enabled: false
        objectStoreRequestUnits:
          addOn: 1
          base: 1
        messaging:
          assigned: 9
        tradingPartnersProduction:
          assigned: 5
        muleDxEDA:
          enabled: false
        angGovernance:
          level: -1
        anypointSecurityTokenization:
          enabled: false
        hybrid:
          enabled: false
        cloudhub1:
          enabled: false
        apis:
          enabled: false
        staticIps:
          reassigned: 4
          assigned: 1
        idp:
          enabled: false
        runtimeFabricCloud:
          enabled: false
        muleDxWebIde:
          enabled: false
        kpiDashboard:
          enabled: false
        autoscaling: true
        partnersSandbox:
          assigned: 7
        externalIdentity: true
        usageBasedPricing:
          muleRuntimeIntegration:
            flows: 7
            messages: 6
            throughput: 0
            enabled: false
        hybridAutoDiscoverProperties: true
        vpns:
          reassigned: 6
          assigned: 2
        muleDxGenAI:
          enabled: false
        runtimeFabric: true
        serviceMesh:
          enabled: false
        cam:
          enabled: false
        anypointSecurityEdgePolicies:
          enabled: false
        pcf: true
        armAlerts: true
        createSubOrgs: true
        loadBalancer:
          reassigned: 7
          assigned: 2
        mqMessages:
          addOn: 1
          base: 1
        vCoresSandbox:
          reassigned: 3.5571952270680973
          assigned: 6.438423552598547
        createEnvironments: true
        rpa:
          active: true
          composerVersion: composerVersion
          enabled: true
        apiMonitoring:
          schedules: 0
        composer:
          unlimitedConnectors: true
          tasksPerMonth: 7
          maxConnectors: 0
          isHyperAutomation: true
          enabled: true
        tradingPartnersSandbox:
          assigned: 9
        apiCatalog:
          enabled: false
        managedGatewayLarge:
          reassigned: 7
          assigned: 3
        mqRequests:
          addOn: 1
          base: 1
        apiQueryC360:
          enabled: false
        apiGovernanceDomain:
          domain: domain
        partnersProduction:
          assigned: 6
        exchange2:
          enabled: true
          assetUsageAndEngagement:
            enabled: true
        mqAdvancedFeatures:
          enabled: false
        vCoresProduction:
          reassigned: 9.018348186070783
          assigned: 8.762042012749001
        crowdSelfServiceMigration:
          enabled: false
        designCenter:
          apiVisual: true
          api: true
          apiExample: true
          mozart: true
      properties:
        angGovernance:
          $ref: '#/components/schemas/AngGovernanceEntitlement'
        anypointSecurityEdgePolicies:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        anypointSecurityTokenization:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        apiCommunityManager:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        apiMonitoring:
          $ref: '#/components/schemas/ApiMonitoringEntitlement'
        apiQuery:
          $ref: '#/components/schemas/ApiQueryEntitlement'
        apiQueryC360:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        apis:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        appViz:
          description: AppViz entitlements
          title: appViz
          type: boolean
        armAlerts:
          description: ARM Alerts entitlements
          title: armAlerts
          type: boolean
        autoscaling:
          description: Autoscaling entitlements
          title: autoscaling
          type: boolean
        cam:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        createEnvironments:
          description: Create Environments entitlements
          title: createEnvironments
          type: boolean
        createSubOrgs:
          description: Create Sub Orgs entitlements
          title: createSubOrgs
          type: boolean
        crowd:
          $ref: '#/components/schemas/CrowdEntitlement'
        crowdSelfServiceMigration:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        designCenter:
          $ref: '#/components/schemas/DesignCenterEntitlement'
        exchange2:
          $ref: '#/components/schemas/Exchange2Entitlement'
        externalIdentity:
          description: External Identity entitlements
          title: externalIdentity
          type: boolean
        gateways:
          $ref: '#/components/schemas/GatewaysEntitlement'
        globalDeployment:
          description: Global Deployment entitlements
          title: globalDeployment
          type: boolean
        hybrid:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        hybridAutoDiscoverProperties:
          description: Hybrid auto-discover properties
          title: hybridAutoDiscoverProperties
          type: boolean
        hybridInsight:
          description: Hybrid Insight entitlements
          title: hybridInsight
          type: boolean
        kpiDashboard:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        loadBalancer:
          $ref: '#/components/schemas/LoadBalancerEntitlement'
        messaging:
          $ref: '#/components/schemas/MessagingEntitlement'
        monitoringCenter:
          $ref: '#/components/schemas/MonitoringCenterEntitlement'
        mqAdvancedFeatures:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        mqMessages:
          $ref: '#/components/schemas/AddOnEntitlement'
        mqRequests:
          $ref: '#/components/schemas/AddOnEntitlement'
        objectStoreKeys:
          $ref: '#/components/schemas/AddOnEntitlement'
        objectStoreRequestUnits:
          $ref: '#/components/schemas/AddOnEntitlement'
        partnersProduction:
          $ref: '#/components/schemas/PartnersProductionEntitlement'
        partnersSandbox:
          $ref: '#/components/schemas/PartnersSandboxEntitlement'
        pcf:
          description: PCF entitlements
          title: pcf
          type: boolean
        runtimeFabric:
          description: Runtime Fabric entitlements
          title: runtimeFabric
          type: boolean
        runtimeFabricCloud:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        serviceMesh:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        staticIps:
          $ref: '#/components/schemas/StaticIpsEntitlement'
        tradingPartnersProduction:
          $ref: '#/components/schemas/TradingPartnersProductionEntitlement'
        tradingPartnersSandbox:
          $ref: '#/components/schemas/TradingPartnersSandboxEntitlement'
        vCoresDesign:
          $ref: '#/components/schemas/vCoresDesignEntitlement'
        vCoresProduction:
          $ref: '#/components/schemas/vCoresProductionEntitlement'
        vCoresSandbox:
          $ref: '#/components/schemas/vCoresSandboxEntitlement'
        vpcs:
          $ref: '#/components/schemas/VpcsEntitlement'
        vpns:
          $ref: '#/components/schemas/VpnsEntitlement'
        workerClouds:
          $ref: '#/components/schemas/WorkerCloudsEntitlement'
        workerLoggingOverride:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        muleDxWebIde:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        muleDxGenAI:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        muleDxEDA:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        highAvailability:
          $ref: '#/components/schemas/HighAvailabilityEntitlement'
        cloudhub1:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        apiGovernance:
          $ref: '#/components/schemas/ApiGovernanceEntitlement'
        apiGovernanceDomain:
          $ref: '#/components/schemas/ApiGovernanceDomainEntitlement'
        apiCatalog:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        apiManager:
          $ref: '#/components/schemas/ApiManagerEntitlement'
        composer:
          $ref: '#/components/schemas/ComposerEntitlement'
        rpa:
          $ref: '#/components/schemas/RpaEntitlement'
        idp:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        usageBasedPricing:
          $ref: '#/components/schemas/UsageBasedPricingEntitlement'
        usageBasedPricingLimits:
          $ref: '#/components/schemas/UsageBasedPricingLimitsEntitlement'
        telemetryExporter:
          $ref: '#/components/schemas/EnablementResourceEntitlement'
        managedGatewaySmall:
          $ref: '#/components/schemas/ManagedGatewaySmallEntitlement'
        managedGatewayLarge:
          $ref: '#/components/schemas/ManagedGatewayLargeEntitlement'
        networkConnections:
          $ref: '#/components/schemas/NetworkConnectionsEntitlement'
      title: entitlements
      type: object
    EntitlementsCore:
      description: Entitlements core
      example:
        globalDeployment: false
        staticIps:
          reassigned: 4
          assigned: 1
        createSubOrgs: false
        loadBalancer:
          reassigned: 7
          assigned: 2
        vpns:
          reassigned: 6
          assigned: 2
        vCoresSandbox:
          reassigned: 3.5571952270680973
          assigned: 6.438423552598547
        vCoresProduction:
          reassigned: 9.018348186070783
          assigned: 8.762042012749001
        createEnvironments: false
        vCoresDesign:
          reassigned: 6.683562403749608
          assigned: 9.369310271410669
        vpcs:
          reassigned: 1
          assigned: 6
      properties:
        globalDeployment:
          default: false
          description: Global Deployment
          title: globalDeployment
          type: boolean
        createEnvironments:
          default: false
          description: Create Environments
          title: createEnvironments
          type: boolean
        createSubOrgs:
          default: false
          description: Create Sub Orgs
          title: createSubOrgs
          type: boolean
        loadBalancer:
          $ref: '#/components/schemas/LoadBalancerEntitlement'
        staticIps:
          $ref: '#/components/schemas/StaticIpsEntitlement'
        vCoresDesign:
          $ref: '#/components/schemas/vCoresDesignEntitlement'
        vCoresProduction:
          $ref: '#/components/schemas/vCoresProductionEntitlement'
        vCoresSandbox:
          $ref: '#/components/schemas/vCoresSandboxEntitlement'
        vpcs:
          $ref: '#/components/schemas/VpcsEntitlement'
        vpns:
          $ref: '#/components/schemas/VpnsEntitlement'
      title: entitlementsCore
      type: object
    AngGovernanceEntitlement:
      example:
        level: -1
      properties:
        level:
          description: Ang Governance level
          example: -1
          title: level
          type: integer
      type: object
    ApiMonitoringEntitlement:
      example:
        schedules: 0
      properties:
        schedules:
          description: Schedules
          title: schedules
          type: integer
      type: object
    TradingPartnersProductionEntitlement:
      example:
        assigned: 5
      properties:
        assigned:
          default: 0
          description: Trading Partners Production assigned
          title: assigned
          type: integer
      title: tradingPartnersProduction
      type: object
    TradingPartnersSandboxEntitlement:
      example:
        assigned: 9
      properties:
        assigned:
          default: 0
          description: Trading Partners Sandbox assigned
          title: assigned
          type: integer
      title: tradingPartnersSandbox
      type: object
    LoadBalancerEntitlement:
      example:
        reassigned: 7
        assigned: 2
      properties:
        assigned:
          default: 0
          description: Load Balancers assigned
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: Load Balancers reassigned
          title: reassigned
          type: integer
      title: loadBalancer
      type: object
    StaticIpsEntitlement:
      description: Static IPs entitlements
      example:
        reassigned: 4
        assigned: 1
      properties:
        assigned:
          default: 0
          description: Static IPs assigned
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: Static IPs reassigned
          title: reassigned
          type: integer
      type: object
    VpnsEntitlement:
      example:
        reassigned: 6
        assigned: 2
      properties:
        assigned:
          default: 0
          description: VPNs assigned
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: VPNs reassigned
          title: reassigned
          type: integer
      title: vpn
      type: object
    VpcsEntitlement:
      example:
        reassigned: 1
        assigned: 6
      properties:
        assigned:
          default: 0
          description: VPCs assigned
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: VPCs reassigned
          title: reassigned
          type: integer
      title: vpc
      type: object
    vCoresProductionEntitlement:
      example:
        reassigned: 9.018348186070783
        assigned: 8.762042012749001
      properties:
        assigned:
          default: 0
          description: VCores Production assigned
          title: assigned
          type: number
        reassigned:
          default: 0
          description: VCores Production reassigned
          title: reassigned
          type: number
      title: vCoresProduction
      type: object
    vCoresDesignEntitlement:
      example:
        reassigned: 6.683562403749608
        assigned: 9.369310271410669
      properties:
        assigned:
          default: 0
          description: VCores Design assigned
          title: assigned
          type: number
        reassigned:
          default: 0
          description: VCores Design reassigned
          title: reassigned
          type: number
      title: vCoresDesign
      type: object
    vCoresSandboxEntitlement:
      example:
        reassigned: 3.5571952270680973
        assigned: 6.438423552598547
      properties:
        assigned:
          default: 0
          description: VCores Sandbox assigned
          title: assigned
          type: number
        reassigned:
          default: 0
          description: VCores Sandbox reassigned
          title: reassigned
          type: number
      title: vCoresSandbox
      type: object
    WorkerCloudsEntitlement:
      example:
        reassigned: 5
        assigned: 6
      properties:
        assigned:
          default: 0
          description: Worker Clouds assigned
          title: assigned
          type: integer
        reassigned:
          default: 0
          description: Worker Clouds reassigned
          title: reassigned
          type: integer
      title: workerClouds
      type: object
    MessagingEntitlement:
      description: Messaging entitlements
      example:
        assigned: 9
      properties:
        assigned:
          default: 0
          description: Messaging assigned
          title: assigned
          type: integer
      title: messaging
      type: object
    MonitoringCenterEntitlement:
      description: Monitoring Center entitlements
      example:
        preProductionUnits: 1.2315135367772556
        productSKU: 3
        storageAddOn: 4.145608029883936
        storageBase: 2.027123023002322
        productionUnits: 7.386281948385884
        dataRegion: dataRegion
      properties:
        productSKU:
          description: Product SKU
          title: productSKU
          type: integer
        dataRegion:
          description: Data region
          title: dataRegion
          type: string
        storageBase:
          description: Storage base
          title: storageBase
          type: number
        storageAddOn:
          description: Storage add-on
          title: storageAddOn
          type: number
        productionUnits:
          description: Production units
          title: productionUnits
          type: number
        preProductionUnits:
          description: Pre-production units
          title: preProductionUnits
          type: number
      title: monitoringCenter
      type: object
    PartnersSandboxEntitlement:
      description: Partners Sandbox entitlements
      example:
        assigned: 7
      properties:
        assigned:
          description: Partners Sandbox assigned
          title: assigned
          type: integer
      title: partnersSandbox
      type: object
    GatewaysEntitlement:
      description: Gateway entitlements
      example:
        assigned: 5
      properties:
        assigned:
          default: 0
          description: Gateway assigned
          title: assigned
          type: integer
      title: gateways
      type: object
    PartnersProductionEntitlement:
      description: Partners Production entitlements
      example:
        assigned: 6
      properties:
        assigned:
          default: 0
          description: Partners Production assigned
          title: assigned
          type: integer
      title: partnersProduction
      type: object
    EnablementResourceEntitlement:
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: Whether entitlement resource is enabled
          title: enabled
          type: boolean
      title: enablementResource
      type: object
    AddOnEntitlement:
      example:
        addOn: 1
        base: 1
      properties:
        addOn:
          default: 0
          description: Add-on
          title: addOn
          type: integer
        base:
          default: 0
          description: Base
          title: base
          type: integer
      type: object
    ApiManagerEntitlement:
      example:
        usageBasedPricing:
          api:
            production:
              amount: 3
            sandbox:
              amount: 3
        governance:
          enabled: false
      properties:
        governance:
          $ref: '#/components/schemas/governance'
        usageBasedPricing:
          $ref: '#/components/schemas/usageBasedPricing'
      type: object
    ComposerEntitlement:
      example:
        unlimitedConnectors: true
        tasksPerMonth: 7
        maxConnectors: 0
        isHyperAutomation: true
        enabled: true
      properties:
        enabled:
          description: Composer enabled
          title: enabled
          type: boolean
        tasksPerMonth:
          description: Tasks per month
          title: tasksPerMonth
          type: integer
        maxConnectors:
          description: Max connectors
          title: maxConnectors
          type: integer
        unlimitedConnectors:
          description: Unlimited connectors
          title: unlimitedConnectors
          type: boolean
        isHyperAutomation:
          description: Hyper Automation
          title: hyperAutomation
          type: boolean
      type: object
    RpaEntitlement:
      example:
        active: true
        composerVersion: composerVersion
        enabled: true
      properties:
        enabled:
          description: RPA enabled
          title: enabled
          type: boolean
        active:
          description: RPA active
          title: active
          type: boolean
        composerVersion:
          description: Composer version
          title: composerVersion
          type: string
      type: object
    UsageBasedPricingEntitlement:
      example:
        muleRuntimeIntegration:
          flows: 7
          messages: 6
          throughput: 0
          enabled: false
      properties:
        muleRuntimeIntegration:
          $ref: '#/components/schemas/muleRuntimeIntegration'
      type: object
    UsageBasedPricingLimitsEntitlement:
      example:
        memory:
          extra: 8
          base: 4
        cpu:
          extra: 8
          base: 4
      properties:
        cpu:
          $ref: '#/components/schemas/UsageBasedPricingLimitsEntitlement_cpu'
        memory:
          $ref: '#/components/schemas/UsageBasedPricingLimitsEntitlement_cpu'
      type: object
    ApiQueryEntitlement:
      description: API Query entitlements
      example:
        productSKU: 6
        production: 5
        sandbox: 1
        enabled: false
      properties:
        enabled:
          default: false
          description: API Query enabled
          title: enabled
          type: boolean
        productSKU:
          default: 0
          description: Product SKU
          title: productSKU
          type: integer
        sandbox:
          description: Product SKU
          title: productSKU
          type: integer
        production:
          description: Product SKU
          title: productSKU
          type: integer
      type: object
    CrowdEntitlement:
      description: Crowd entitlements
      example:
        environments: false
        hideApiManagerDesigner: false
        hideFormerApiPlatform: false
      properties:
        environments:
          default: false
          description: Crowd environments
          title: environments
          type: boolean
        hideApiManagerDesigner:
          default: false
          description: Crowd Hide API Manager Designer
          title: hideApiManagerDesigner
          type: boolean
        hideFormerApiPlatform:
          default: false
          description: Crowd Hide Former API Platform
          title: hideFormerApiPlatform
          type: boolean
      type: object
    Exchange2Entitlement:
      description: Exchange 2 entitlements
      example:
        enabled: true
        assetUsageAndEngagement:
          enabled: true
      properties:
        enabled:
          description: Exchange 2 enabled
          title: enabled
          type: boolean
        assetUsageAndEngagement:
          $ref: '#/components/schemas/Exchange2Entitlement_assetUsageAndEngagement'
      type: object
    DesignCenterEntitlement:
      description: Design Center entitlements
      example:
        apiVisual: true
        api: true
        apiExample: true
        mozart: true
      properties:
        api:
          description: API entitlements
          title: api
          type: boolean
        mozart:
          description: Mozart entitlements
          title: mozart
          type: boolean
        apiVisual:
          description: API Visual entitlements
          title: apiVisual
          type: boolean
        apiExample:
          description: API Example entitlements
          title: apiExample
          type: boolean
      type: object
    ManagedGatewaySmallEntitlement:
      description: Managed Gateway Small entitlements
      example:
        reassigned: 3
        assigned: 7
      properties:
        assigned:
          description: Managed Gateway Small assigned
          title: assigned
          type: integer
        reassigned:
          description: Managed Gateway Small reassigned
          title: reassigned
          type: integer
      type: object
    ManagedGatewayLargeEntitlement:
      description: Managed Gateway Large entitlements
      example:
        reassigned: 7
        assigned: 3
      properties:
        assigned:
          description: Managed Gateway Large assigned
          title: assigned
          type: integer
        reassigned:
          description: Managed Gateway Large reassigned
          title: reassigned
          type: integer
      type: object
    NetworkConnectionsEntitlement:
      description: Network connections entitlements
      example:
        reassigned: 3
        assigned: 5
      properties:
        assigned:
          description: Network connections assigned
          title: assigned
          type: integer
        reassigned:
          description: Network connections reassigned
          title: reassigned
          type: integer
      type: object
    ApiGovernanceEntitlement:
      example:
        apisPerMonth: 6
        enabled: true
      properties:
        enabled:
          description: API Governance enabled
          title: enabled
          type: boolean
        apisPerMonth:
          description: APIs per month
          title: apisPerMonth
          type: integer
      type: object
    ApiGovernanceDomainEntitlement:
      example:
        domain: domain
      properties:
        domain:
          description: API Governance domain
          title: domain
          type: string
      type: object
    HighAvailabilityEntitlement:
      example:
        clustering: true
      properties:
        clustering:
          description: Clustering
          title: clustering
          type: boolean
      type: object
    Usage:
      example:
        networkConnectionsConsumed: 7
        productionVCoresConsumed: 0.8008281904610115
        sandboxVCoresConsumed: 6.027456183070403
        staticIpsConsumed: 5.962133916683182
        vpcsConsumed: 5
        designVCoresConsumed: 1.4658129805029452
        loadbalancerWorkersConsumed: 3
        loadBalancersConsumed: 9
        vpnsConsumed: 2
      properties:
        productionVCoresConsumed:
          default: 0
          description: Production VCores consumed
          title: productionVCoresConsumed
          type: number
        sandboxVCoresConsumed:
          default: 0
          description: Sandbox VCores consumed
          title: sandboxVCoresConsumed
          type: number
        designVCoresConsumed:
          default: 0
          description: Design VCores consumed
          title: designVCoresConsumed
          type: number
        staticIpsConsumed:
          default: 0
          description: Static IPs consumed
          title: staticIpsConsumed
          type: number
        vpcsConsumed:
          default: 0
          description: VPCs consumed
          title: vpcsConsumed
          type: integer
        vpnsConsumed:
          default: 0
          description: VPNs consumed
          title: vpnsConsumed
          type: integer
        networkConnectionsConsumed:
          default: 0
          description: Network connections consumed
          title: networkConnectionsConsumed
          type: integer
        loadBalancersConsumed:
          default: 0
          description: Load balancers consumed
          title: loadBalancersConsumed
          type: integer
        loadbalancerWorkersConsumed:
          default: 0
          description: Load balancer workers consumed
          title: loadbalancerWorkersConsumed
          type: integer
      type: object
    subscription:
      description: The subscription details of the organization.
      properties:
        category:
          default: ""
          description: The category of the subscription.
          title: category
          type: string
        expiration:
          default: ""
          description: The expiration date of the subscription.
          title: expiration
          type: string
        type:
          default: ""
          description: The type of the subscription.
          title: type
          type: string
      title: subscription
      type: object
      example: null
    masterBGSpecificDetails:
      properties:
        sessionTimeout:
          default: 0
          description: The session timeout in minutes.
          title: sessionTimeout
          type: integer
        subscription:
          $ref: '#/components/schemas/subscription'
        gdotId:
          default: ""
          description: The gdot id of the organization
          title: gdotId
          type: string
        deletedAt:
          description: The deleted date of the organization
          nullable: true
          title: deletedAt
          type: string
        orgType:
          default: ""
          description: The type of the organization
          title: orgType
          type: string
      title: masterBGSpecificDetails
      type: object
      example: null
    governance:
      example:
        enabled: false
      properties:
        enabled:
          default: false
          description: API Manager governance enabled
          title: enabled
          type: boolean
      title: governance
      type: object
    production:
      example:
        amount: 3
      properties:
        amount:
          default: 0
          description: Amount
          title: amount
          type: integer
      title: production
      type: object
    sandbox:
      example:
        amount: 3
      properties:
        amount:
          default: 0
          description: Amount
          title: amount
          type: integer
      title: sandbox
      type: object
    api:
      example:
        production:
          amount: 3
        sandbox:
          amount: 3
      properties:
        production:
          $ref: '#/components/schemas/production'
        sandbox:
          $ref: '#/components/schemas/sandbox'
      title: api
      type: object
    usageBasedPricing:
      example:
        api:
          production:
            amount: 3
          sandbox:
            amount: 3
      properties:
        api:
          $ref: '#/components/schemas/api'
      title: usageBasedPricing
      type: object
    muleRuntimeIntegration:
      example:
        flows: 7
        messages: 6
        throughput: 0
        enabled: false
      properties:
        enabled:
          default: false
          description: Mule Runtime Integration enabled
          title: enabled
          type: boolean
        flows:
          default: 0
          description: Flows
          title: flows
          type: integer
        messages:
          default: 0
          description: Messages
          title: messages
          type: integer
        throughput:
          default: 0
          description: Throughput
          title: throughput
          type: integer
      title: muleRuntimeIntegration
      type: object
    UsageBasedPricingLimitsEntitlement_cpu:
      example:
        extra: 8
        base: 4
      properties:
        base:
          default: 0
          description: Base
          title: base
          type: integer
        extra:
          default: 0
          description: Extra
          title: extra
          type: integer
      type: object
    Exchange2Entitlement_assetUsageAndEngagement:
      example:
        enabled: true
      properties:
        enabled:
          description: Asset usage and engagement enabled
          title: enabled
          type: boolean
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
